/** Short labels for TOC and slideshow navigation (matches ethicalAiGuideSlides.json order, 28 slides). */
export const ETHICAL_AI_SLIDE_TITLES: string[] = [
  'The Ethical Researcher’s Guide to AI (2026)',
  'What we’ll explore — navigation',
  'Chapter 1: Understanding AI detection',
  'How AI detection tools work',
  'Detection accuracy & false positives',
  'Why “removing AI detection” is the wrong question',
  'Chapter 2: Ethical AI tools',
  'Humanizer tools vs reality',
  'Chapter 3: Writing with integrity',
  'Allowed vs prohibited AI use',
  'Brainstorming & topic development',
  'Structuring & outlining',
  'Clarity, style & editing',
  'Chapter 4: Literature review with AI',
  'AI as a literature review assistant',
  'What AI cannot do for literature reviews',
  'Visual slide (original presentation)',
  'Finding & verifying sources',
  'Chapter 5: Citation & transparency',
  'Why disclosure matters',
  'How to cite AI (APA, MLA, Chicago, IEEE)',
  'University AI policies',
  'Chapter 6: Your ethical AI workflow',
  'Researcher’s AI toolkit',
  'Step-by-step ethical writing process',
  'Red flags & unethical use',
  'ChatGPT, Turnitin & universities in India',
  'Golden rules — conclusion',
];
