// Gaply — Research Paper Writer: the LaTeX export.
//
// WHAT THIS PRODUCES, and the honesty that governs it. A .zip containing a
// `main.tex` built on the GENERIC `article` class with a per-scaffold preamble —
// never `IEEEtran`, `acmart`, `llncs` or any publisher's own class. Four reasons
// that compound: we cannot ship those class files (publisher-licensed), a .tex
// naming one fails to build on a minimal TeX install, several scaffolds have no
// official class at all, and a file opening `\documentclass{acmart}` IS claiming
// to be an ACM submission. The generic class is what makes the output
// structurally unable to pose as an official template.
//
// The two-column result is a READING LAYOUT — "see your paper the way a reader
// will" — not the submission artefact. That framing is why the product's four
// standing claims stay true as written: Gaply still formats structure and
// references, the publisher still typesets the final article, and the submission
// export remains the single-column manuscript. The header comment says so, in
// the file, because a .tex outlives the app that wrote it, and tells the author
// the one edit that switches it (`twocolumn` → `onecolumn`).
//
// THE BIBLIOGRAPHY IS PRE-RENDERED, DELIBERATELY. `thebibliography` is baked
// from the SAME citeproc render the editor shows, so the exported [1] is the
// [1] on screen and in the References list — the invariant citationB2 pins. A
// real .bib handed to a .bst would be reformatted by LaTeX in some OTHER style,
// because there is no CSL→bst mapping, and the author would compile a
// bibliography they never saw. `references.bib` is written into the bundle too,
// as a labelled convenience for anyone continuing in Overleaf.
import JSZip from 'jszip';
import { Manuscript, LatexFormat, DEFAULT_LATEX_FORMAT, Scaffold } from './manuscriptModel';
import { CitationRender } from './manuscriptCitations';
import { readImageBytes, imageRefsIn, IMAGE_REF_PREFIX } from './noteImages';
import { sectionBodyToTex, LatexCtx } from './manuscriptLatexBody';
import { proseToTex, texComment, texSafeName } from './latexEscape';

/** Sections that never take a number, mirroring the .docx exporter's set so the
 *  two formats agree about what is front and back matter. */
const UNNUMBERED_KEYS = new Set(['abstract', 'keywords', 'index_terms', 'ccs_concepts', 'author_summary', 'references']);

export interface LatexBundle {
  /** path inside the zip → contents */
  files: Map<string, string | Uint8Array>;
}

const preamble = (f: LatexFormat, scaffold: Scaffold): string => {
  const opts = [`${f.fontSizePt}pt`, f.pageSize === 'a4' ? 'a4paper' : 'letterpaper'];
  if (f.columns === 2) opts.push('twocolumn');
  return [
    `\\documentclass[${opts.join(',')}]{article}`,
    '',
    '% --- packages -------------------------------------------------------',
    '\\usepackage[T1]{fontenc}',
    '\\usepackage[utf8]{inputenc}',
    '\\usepackage{amsmath,amssymb}   % the math subset Gaply accepts',
    '\\usepackage{graphicx}',
    // `max width` never UPSCALES: a small pasted screenshot keeps its own size
    // instead of being blown up to the full column, which is what plain
    // `width=\\linewidth` does and it looks absurd.
    '\\usepackage[export]{adjustbox}',
    '\\usepackage{booktabs}',
    '\\usepackage[normalem]{ulem}    % \\sout for struck-through text',
    '\\usepackage{url}',
    '\\usepackage[hidelinks]{hyperref}',
    `\\usepackage[margin=${f.marginInch}in]{geometry}`,
    f.lineNumbers ? '\\usepackage{lineno}\n\\linenumbers' : '',
    '',
    '% --- structure ------------------------------------------------------',
    f.sectionNumbering === 'none' ? '\\setcounter{secnumdepth}{0}' : '',
    f.sectionNumbering === 'roman-upper' ? '\\renewcommand{\\thesection}{\\Roman{section}}' : '',
    '\\setlength{\\parskip}{0pt}',
    '',
    texComment(`Structure: ${scaffold.label}. ${scaffold.noticeText}`),
    texComment(`Publisher's current author guidance: ${scaffold.publisherAuthorUrl}`),
  ].filter(Boolean).join('\n');
};

/** The header every exported .tex carries. It travels with the file to Overleaf,
 *  to a co-author, into a submission system — which the UI notice does not. */
const honestHeader = (scaffold: Scaffold, f: LatexFormat): string =>
  texComment([
    'Generated by Gaply — Research Paper Writer.',
    '',
    `STRUCTURE: ${scaffold.label}`,
    "This is Gaply's own scaffold, informed by the publisher's PUBLIC author",
    'guidance. It is NOT an official template and this file was NOT produced by',
    `any publisher's class file. It uses the generic "article" class.`,
    '',
    f.columns === 2
      ? [
        'LAYOUT: two-column — a READING layout, so you can see your paper the way',
        'a reader will. It is not a submission artefact and will not match the',
        "venue's typeset article. For submission, use the venue's own class or",
        'Gaply\'s single-column .docx manuscript export.',
        'To switch: change "twocolumn" in \\documentclass below to "onecolumn".',
      ].join('\n')
      : 'LAYOUT: single-column manuscript.',
    '',
    'REFERENCES: the thebibliography block below is pre-rendered in the style',
    'you chose in Gaply, so it matches the in-text markers exactly. A',
    'references.bib is included in this bundle if you would rather use BibTeX —',
    'note that a .bst will re-format the entries in ITS style, not this one.',
    '',
    `Verify the venue's current requirements: ${scaffold.publisherAuthorUrl}`,
  ].join('\n'));

/** Title block. `\author` carries affiliations and the corresponding address as
 *  a footnote-free block, since a generic class has no venue-specific commands. */
const titleBlock = (m: Manuscript, f: LatexFormat): string => {
  const bits = [`\\title{${proseToTex(m.title.trim() || 'Untitled manuscript')}}`];
  const authorParts = [proseToTex(m.authors.trim())];
  if (f.titleBlock.affiliations && m.affiliations.trim()) authorParts.push(`\\\\ \\small ${proseToTex(m.affiliations.trim())}`);
  if (f.titleBlock.correspondingAuthor && m.correspondingAuthor.trim()) {
    authorParts.push(`\\\\ \\small Corresponding author: ${proseToTex(m.correspondingAuthor.trim())}`);
  }
  bits.push(`\\author{${authorParts.filter(Boolean).join('\n')}}`);
  bits.push('\\date{}');
  return bits.join('\n');
};

/**
 * The reference list, rendered as a plain hanging-indent block.
 *
 * NOT `thebibliography`, and that is the whole point. The entries are already
 * finished text from citeproc — a numbered style's "[1] " prefix is IN the
 * string, an author-date style has no prefix at all. `thebibliography` adds its
 * own bracketed counter to every entry, which produced "[1] [1] K. He, …" for
 * IEEE and numbered an APA list that must not be numbered. It also emits its own
 * "References" heading, so the section came out headed twice.
 *
 * A hanging-indent group adds nothing of its own, so what compiles is exactly
 * what the editor displayed — which is the invariant this export exists to keep.
 */
const bibliographyBlock = (cites: CitationRender): string => {
  const entries = cites.bibliography.split('\n').map((l) => l.trim()).filter(Boolean);
  if (entries.length === 0) return '';
  return [
    '\\begingroup',
    '\\setlength{\\parindent}{0pt}',
    '\\setlength{\\parskip}{0.4em}',
    ...entries.map((e) => `\\hangindent=1.5em\\hangafter=1 ${proseToTex(e)}\\par`),
    '\\endgroup',
  ].join('\n');
};

export interface BuildLatexOptions {
  /** Injectable for tests; defaults to reading the real image files. */
  readImage?: (ref: string) => Promise<{ data: Uint8Array; mime: string }>;
}

/**
 * Build the complete bundle. Returns a path → contents map; the caller writes
 * it as a .zip (or, in tests, inspects it directly).
 */
export async function buildLatexBundle(
  m: Manuscript,
  scaffold: Scaffold,
  format: LatexFormat = DEFAULT_LATEX_FORMAT,
  citations?: CitationRender,
  bibtex?: string,
  opts: BuildLatexOptions = {},
): Promise<LatexBundle> {
  const files = new Map<string, string | Uint8Array>();
  const readImage = opts.readImage ?? readImageBytes;

  // Figures first, so the body walk can reference real filenames. Named by
  // position rather than by hash: "figures/figure-1.png" is what an author
  // expects to find, and the hash means nothing outside Gaply.
  const figures = new Map<string, string>();
  const allRefs = m.sections.flatMap((s) => imageRefsIn(s.body));
  const uniqueRefs = allRefs.filter((r, i) => allRefs.indexOf(r) === i);
  let figureNo = 0;
  for (const ref of uniqueRefs) {
    const ext = ref.slice(IMAGE_REF_PREFIX.length).split('.').pop() ?? 'png';
    const name = `figures/figure-${++figureNo}.${ext}`;
    try {
      const { data } = await readImage(ref);
      if (data.length) { files.set(name, data); figures.set(ref, name); }
    } catch {
      // An unreadable image degrades to an honest placeholder in the body
      // rather than a \includegraphics pointing at a file that is not there,
      // which would fail the build with a confusing error.
      figureNo -= 1;
    }
  }

  const ctx: LatexCtx = { citations, counter: { i: 0 }, figures, figureOrder: [] };
  const cited = !!citations?.hasCitations;
  const bib = cited ? bibliographyBlock(citations!) : '';

  const body: string[] = [];
  let refsEmitted = false;
  for (const s of m.sections) {
    // Mirrors the .docx rule exactly, including its hard-won edge case: when
    // every citation is dangling the rendered bibliography is empty, and the
    // author's hand-written References text is then the only reference text
    // that exists — so it must still ship.
    if (s.key === 'references' && cited && bib) {
      body.push(`\\section*{${proseToTex(s.heading)}}`, bib);
      refsEmitted = true;
      continue;
    }
    const tex = sectionBodyToTex(s.body, ctx);
    if (!tex.trim()) continue; // honest skip — no empty heading
    const cmd = UNNUMBERED_KEYS.has(s.key) || format.sectionNumbering === 'none' ? 'section*' : 'section';
    body.push(`\\${cmd}{${proseToTex(s.heading)}}`, tex);
  }
  if (cited && bib && !refsEmitted) body.push('\\section*{References}', bib);

  const tex = [
    honestHeader(scaffold, format),
    '',
    preamble(format, scaffold),
    '',
    titleBlock(m, format),
    '',
    '\\begin{document}',
    '\\maketitle',
    '',
    body.join('\n\n'),
    '',
    '\\end{document}',
    '',
  ].join('\n');

  files.set('main.tex', tex);
  if (bibtex && bibtex.trim()) files.set('references.bib', bibtex);
  files.set('README.txt', [
    'Gaply — LaTeX export',
    '',
    'main.tex        the manuscript. Compile with: latexmk -pdf main.tex',
    files.has('references.bib') ? 'references.bib  your cited references in BibTeX, for use in Overleaf.' : '',
    uniqueRefs.length ? 'figures/        the images from your manuscript.' : '',
    '',
    'main.tex uses the generic "article" class, not a publisher template.',
    'See the comment block at the top of main.tex for what that means.',
  ].filter(Boolean).join('\n'));

  return { files };
}

/** Bundle → a real .zip blob. jszip already ships as a dependency of docx. */
export async function bundleToZip(bundle: LatexBundle): Promise<Blob> {
  const zip = new JSZip();
  bundle.files.forEach((contents, path) => zip.file(path, contents));
  return zip.generateAsync({ type: 'blob' });
}

/** Save the bundle via the native dialog (Tauri) or a browser download.
 *  Returns the saved path, or null on cancel / in a browser. */
export async function saveLatexBundle(bundle: LatexBundle, suggestedName: string): Promise<string | null> {
  const blob = await bundleToZip(bundle);
  const { isTauri } = await import('../../utils/isTauri');
  if (isTauri) {
    const { save } = await import('@tauri-apps/plugin-dialog');
    const path = await save({ defaultPath: suggestedName, filters: [{ name: 'LaTeX bundle', extensions: ['zip'] }] });
    if (!path) return null;
    const { writeFile } = await import('@tauri-apps/plugin-fs');
    await writeFile(path, new Uint8Array(await blob.arrayBuffer()));
    return path;
  }
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = suggestedName;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
  return null;
}

export { texSafeName };
